apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
  namespace: mongo-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      restartPolicy: Always
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom: 
              secretKeyRef: 
                 name: mongo-secret
                 key: username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom: 
                secretKeyRef: 
                  name: mongo-secret
                  key: password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom: 
                configMapKeyRef: 
                  name: mongo-configmap
                  key: mongo-server
          - name: ME_CONFIG_MONGODB_PORT
            valueFrom: 
                configMapKeyRef: 
                  name: mongo-configmap
                  key: mongo-port
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: mongo-ns
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001                  