apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: mongo-ns
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017